### ISSUE TITLE
Re-runs aggregate on the plot

### ISSUE THREAD

**Issue by RoxaneLS** [nilesh-tawari/ChronQC#3]
Hi Nilesh, we've been using ChronQC in my diagnostic lab for a little while now and we noticed one problem: When a run fails in the pipeline and we need to re-run it, the command `chronqc database --update` adds the new values for that run on top of the previous data point for that same run, instead of replacing it. That makes the plot legend messy and hard to read. See screenshot attached.
![screenshot](https://user-images.githubusercontent.com/13159414/58523048-49bc4280-8206-11e9-9c08-d46f1b122061.png)

Is there a way to "clean up" the database for a given run, before re-adding it?

Thanks!
Roxane

**Comment by nilesh-tawari** [comment]
Hi Roxane, we need to do this manually as there is now way to know automatically which values to keep. I would suggest using any SQLite viewer to correct database.
